### ISSUE TITLE
Application crashed

### ISSUE THREAD

**Issue by DefinitlyEvil** [222464/NeoRL#1]
I compiled it using CMAKE and Visual Studio 2015 but when I try to run it, it crashed after displaying my hardware info. 

I used SMFL 2.3.2 and latest OpenCL for Intel. 

All examples are faild to run, for example, TextPrediction will fail at main() line 49: 
```C++
std::string test(size, ' ');
```
also in audio generation example I got: 
`Unhandled exception at 0x00007FFB9F991BC9 (OpenCL.dll) in NeoRL.exe: 0xC0000005: Access violation reading location 0x00000000FFFFFFDC.`

**Comment by 222464** [comment]
I worked together with DefinitlyEvil, we found it was a bad OpenCL installation.
