### ISSUE TITLE
Install openCL for Ubuntu x86

### ISSUE THREAD

**Issue by StasiaS** [222464/NeoRL#2]
Hello!

Help me please with install OpenCL. I have got Ubuntu 14.04 (32-bit) and Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz.
But on your links https://software.intel.com/en-us/intel-opencl I found only for Ubuntu(64-bit).

Ann

**Comment by 222464** [comment]
Hello!

I found that you can use the AMD APP SDK for Intel CPUs as well. Give that a try!

**Comment by StasiaS** [comment]
Thank you for your answer!

Today I use AMD APP SDK, but I have got next Error:

CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindOpenCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCL" with any
  of the following names:

    OpenCLConfig.cmake
    opencl-config.cmake

  Add the installation prefix of "OpenCL" to CMAKE_PREFIX_PATH or set
  "OpenCL_DIR" to a directory containing one of the above files.  If "OpenCL"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!


How can I fix it problem?

**Comment by StasiaS** [comment]
I find my problem. Now I run with root. And cmake work without problem.
