### ISSUE TITLE
AgentCACLA.h is missing

### ISSUE THREAD

**Issue by bnurbekov** [222464/NeoRL#6]
Hi,

Thank you very much for NeoRL. It's awesome!
I saw some references to AgentCACLA.h in balancing demo. However, I cannot find it under neo folder for some reason. If is not yet implemented, can you explain how continuous state and action spaces will work with NeoRL? I just wanted to try running cart-pole balancing task.

Thank you!

**Comment by 222464** [comment]
Sorry for the late response! It was implemented, but removed again since it didn't work well. NeoRL will receive a large update soon.

**Comment by Thanh-Binh** [comment]
I am very happy, if a large update will come asap.
Why do not you update it stepwise?
What new?
